### ISSUE TITLE
Parsing full English-style dates

### ISSUE THREAD

**Issue by olivierlacan** [tech-angels/vandamme#10]
I know the formatting guidelines state that dates _must_ be formatted with the ISO format but I'm curious if it would be feasible to parse "full" dates like: April 18th, 2014. The ordinal suffix is surely a pain to deal with but I find myself thinking it's much easier to parse than even the ISO format and it's clearly not as ambiguous as the localized short formats (04/18/14, 18/04/14). 

Example: https://github.com/skylightio/skylight-ruby/blob/master/CHANGELOG.md

**Comment by gravis** [comment]
Good idea!
Thanks for the suggestion :)
